first/dbr/urls.py
from django.conf.urls import url
from dbr import views
from django.urls import path
from django.views.generic import TemplateView

app_name = 'dbr'
urlpatterns = [
    #path('', views.index,name='index'),
    path('register', views.register,name='register'),
    path('', views.user_login,name='login'),
    path('logout', views.user_logout,name='logout'),
    path('dashboard', views.dashboard,name='dashboard'),
    #path('date/', TemplateView.as_view(template_name='dbr/date.html'),name='date'),
    path('date', views.date,name='date'),
    path('roaster', views.roaster,name='roaster'),
]

first/first/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from dbr import urls
from dbr import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dbr/', include('dbr.urls')),
    path('', views.user_login, name='login')
]

first/dbr/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)


    def __str__(self):
        return self.user.username


class DbaRoaster(models.Model):
    date = models.DateField(primary_key=True)
    day = models.CharField(max_length=25, blank=True, null=True)
    deepak = models.CharField(max_length=25, blank=True, null=True)
    nainesh = models.CharField(max_length=25, blank=True, null=True)
    akhilesh = models.CharField(max_length=25, blank=True, null=True)
    gaurav = models.CharField(max_length=25, blank=True, null=True)
    pranav = models.CharField(max_length=25, blank=True, null=True)
    prashant = models.CharField(max_length=25, blank=True, null=True)
    rohan = models.CharField(max_length=25, blank=True, null=True)
    shreeyash = models.CharField(max_length=25, blank=True, null=True)
    ankit = models.CharField(max_length=25, blank=True, null=True)
    ashvini = models.CharField(max_length=25, blank=True, null=True)
    kripa = models.CharField(max_length=25, blank=True, null=True)
    siddesh = models.CharField(max_length=25, blank=True, null=True)
    biki = models.CharField(max_length=25, blank=True, null=True)
    sumit = models.CharField(max_length=25, blank=True, null=True)
    mrunal = models.CharField(max_length=25, blank=True, null=True)
    pritam = models.CharField(max_length=25, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dba_roaster'

first/dbr/forms.py
from django import forms
from django.contrib.auth.models import User
from dbr.models import UserProfile,DbaRoaster
from django.forms.widgets import DateInput


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('first_name','last_name','username','email','password')


class DateForm(forms.ModelForm):

    class Meta():
        model = DbaRoaster
        fields = ('date',)
        widgets = {
            'date': DateInput(attrs={'type': 'date'})
        }

first/dbr/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from dbr.models import UserProfile,DbaRoaster
from dbr.forms import UserForm, DateForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

# Create your views here.


def index(request):
    user_list = User.objects.order_by('id')
    user_dict={'user_list':user_list}
    return render(request,'dbr/index.html', context=user_dict)

def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()


            registered = True
        else:
            print(user_form.errors)

    else:
        user_form = UserForm()

    return render(request,'dbr/register.html',
                        {'user_form':user_form,
                         'registered':registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('dbr:dashboard'))
                #return render(request,'dbr/index.html')

            else:
                return HttpResponse('Account Not ACTIVE')

        else:
            print("Login Failed")
            print("Username {} and Password {}".format(username,password))
            return HttpResponse('Invalid Login Details')


    else:
        return render(request,'dbr/login.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('dbr:login'))

def dashboard(request):
    user_list = User.objects.order_by('id')
    user_dict={'user_list':user_list}
    return render(request,'dbr/dashboard.html', context=user_dict)

def date(request):
    if request.method == 'POST':
        date_form = DateForm(request.POST)
        if date_form.is_valid():
            date = date_form.save(commit=False)
            return ('roaster')
    else:
        date_form = DateForm()

    return render(request, 'dbr/date.html', {'date_form' :date_form})

    #return render(request, 'dbr/date.html'  {'date_form':date_form})


def roaster(request):
    roaster = DbaRoaster.objects.filter(date=request.POST.get('date', None))
    dba_roaster={'roaster':roaster}
    return render(request,'dbr/roaster.html', context=dba_roaster)

first/templates/dbr/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">DBA Roaster</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'dbr:dashboard' %}">Home</a>
            </li>
            <!--<li class="nav-item">
              <a class="nav-link" href="{% url 'dbr:register' %}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled">Disabled</a>
            </li>-->
          </ul>
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">

            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'dbr:logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'dbr:login' %}">Login</a>
            </li>
            {% endif %}

          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">

      {% block body_block %}

      {% endblock %}

    </div>

    <nav class="navbar navbar-light bg-light">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link disabled">Developed and Maintained by</a>
        </li>
      </ul>
    </nav>


  </body>
</html>

first/templates/dbr/base1.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">DBA Roaster</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">

            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'dbr:logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'dbr:login' %}">Login</a>
            </li>
            {% endif %}

          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">

      {% block body_block %}

      {% endblock %}

    </div>

    <nav class="navbar navbar-light bg-light">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link disabled">Developed and Maintained by</a>
        </li>
      </ul>
    </nav>


  </body>
</html>

first/templates/dbr/dashboard.html
<!DOCTYPE html>
{% extends "dbr/base.html" %}

  {% block body_block %}
    <div class="users">
      <h1>DBA Roaster</h1>
      <h4><a href="{% url 'dbr:date' %}"><input type="submit" name="view_date" value="View by Date"></a></h4>

      <div class="user">

      {% if user_list %}
      <table id="user1">
        <thead>
          <th>User ID</th>
          <th>User Name</th>
          <th>First Name</th>
          <th>Last Name</th>
        </thead>

        {% for d in user_list %}
        <tr>
          <td>{{d.id}}</td>
          <td>{{d.username}}</td>
          <td>{{d.first_name}}</td>
          <td>{{d.last_name}}</td>
        </tr>
        {% endfor %}
      </table>

      {% else %}
      <p>No Record Found</p>
      {% endif %}
      </div>

    </div>

  {% endblock %}

first/templates/dbr/date.html
<!DOCTYPE html>

{% extends "dbr/base.html" %}

{% block body_block %}

<div id='date' class="jumbotron">
  <h4>Choose a Date</h4>

  <form class="" action="{% url 'dbr:roaster' %}" method="post">
    {% csrf_token %}

    {{ date_form.as_p }}
    <p><input type="submit" name="" value="VIEW"></p>
  </form>

</div>

{% endblock %}

first/templates/dbr/index.html
<!DOCTYPE html>

{% extends "dbr/base1.html" %}

{% block body_block %}

<div id='login' class="jumbotron">
  <h2>LOGIN</h2>

  <form class="" action="{% url 'dbr:login' %}" method="post">
    {% csrf_token %}

    <p><label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username"></p>
    <p><label for="password">Password:</label>
    <input type="password" name="password" value=""></p>
    <p><input type="submit" name="" value="LOGIN"></p>
  </form>

</div>

{% endblock %}

first/templates/dbr/index1.html
<!DOCTYPE html>
{% extends "dbr/base.html" %}

  {% block body_block %}

    <h1>DBA Roaster</h1>
    <h2>User List</h2>

    <div class="user">

    {% if user_list %}
    <table>
      <thead>
        <th>User ID</th>
        <th>First Name</th>
        <th>Last Name</th>
      </thead>

      {% for d in user_list %}
      <tr>
        <td>{{d.id}}</td>
        <td>{{d.first_name}}</td>
        <td>{{d.last_name}}</td>
      </tr>
      {% endfor %}
    </table>

    {% else %}
    <p>No Record Found</p>
    {% endif %}
    </div>
  {% endblock %}

first/templates/dbr/register.html
<!DOCTYPE html>

{% extends "dbr/base.html" %}

{% block body_block %}

  <div id='register' class="jumbotron">
    {% if registered %}

      <h2>Thank You for Registering</h2>
      <h3>Please click on login</h3>

    {% else %}

      <h2>Registration</h2>

      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        <input type="submit" name="" value="Register">
      </form>

    {% endif %}
  </div>

{% endblock %}

first/templates/dbr/roaster.html
<!DOCTYPE html>
{% extends "dbr/base.html" %}

  {% block body_block %}


    <div class="roaster">
      <h2>DBA Roaster</h2>
    {% if roaster %}

      {% for d in roaster %}
      <h4>Date - {{d.date}}</h4>
      <h4>Day - {{d.day}}</h4>

      <!--<p>Deepak Nanaware - {{d.deepak}}</p>
      <p>Nainesh More - {{d.nainesh}}</p>
      <p>Akhilesh Tiwari - {{d.akhilesh}}</p>
      <p>Gaurav Kadam - {{d.gaurav}}</p>
      <p>Pranav Morwal - {{d.pranav}}</p>
      <p>Prashant Patil - {{d.prashant}}</p>
      <p>Rohan Nikam - {{d.rohan}}</p>
      <p>Shreeyash Dange - {{d.shreeyash}}</p>
      <p>Ankit Kadam - {{d.ankit}}</p>
      <p>Ashvini Jadhav - {{d.ashvini}}</p>
      <p>Kripa Pathak - {{d.kripa}}</p>
      <p>Siddesh Tambde - {{d.siddesh}}</p>
      <p>Biki Adak - {{d.biki}}</p>
      <p>Sumit Duduskar - {{d.sumit}}</p>
      <p>Mrunal Pallempati - {{d.mrunal}}</p>
      <p>Pritam Bhalerao - {{d.pritam}}</p>-->
      <div class="roaster">
        <table id="roaster1">
          <thead><th>Name</th><th>Shift</th><th>Contact</th></thead>
          <tr><td>Deepak Nanaware</td><td>{{d.deepak}}</td><td><a href="https://wa.me/919699706619">+91 9699706619</a></td></tr>
  	      <tr><td>Nainesh More</td><td>{{d.nainesh}}</td><td><a href="https://wa.me/919403112656">+91 9403112656</a></td></tr>
  	      <tr><td>Akhilesh Tiwari</td><td>{{d.akhilesh}}</td><td><a href="https://wa.me/918329304912">+91 8329304912</a></td></tr>
  	      <tr><td>Gaurav Kadam</td><td>{{d.gaurav}}</td><td><a href="https://wa.me/919870484838">+91 9870484838</a></td></tr>
  	      <tr><td>Pranav Morwal</td><td>{{d.pranav}}</td><td><a href="https://wa.me/917588886186">+91 7588886186</a></td></tr>
  	      <tr><td>Prashant Patil</td><td>{{d.prashant}}</td><td><a href="https://wa.me/919860360495">+91 9860360495</a></td></tr>
  	      <tr><td>Rohan Nikam</td><td>{{d.rohan}}</td><td><a href="https://wa.me/919665399646">+91 9665399646</a></td></tr>
  	      <tr><td>Shreeyash Dange</td><td>{{d.shreeyash}}</td><td><a href="https://wa.me/918452924821">+91 8452924821</a></td></tr>
  	      <tr><td>Ankit Kadam</td><td>{{d.ankit}}</td><td><a href="https://wa.me/918356863366">+91 8356863366</a></td></tr>
  	      <tr><td>Ashvini Jadhav</td><td>{{d.ashvini}}</td><td><a href="#">+91 8379987190</a></td></tr>
  	      <tr><td>Kripa Pathak</td><td>{{d.kripa}}</td><td><a href="#">+91 8369564416</a></td></tr>
  	      <tr><td>Siddesh Tambde</td><td>{{d.siddesh}}</td><td><a href="https://wa.me/918779656236">+91 8779656236</a></td></tr>
  	      <tr><td>Biki Adak</td><td>{{d.biki}}</td><td><a href="https://wa.me/919619386633">+91 9619386633</a></td></tr>
  	      <tr><td>Sumit Duduskar</td><td>{{d.sumit}}</td><td><a href="https://wa.me/917208441709">+91 7208441709</a></td></tr>
  	      <tr><td>Mrunal Pallempati</td><td>{{d.mrunal}}</td><td><a href="https://wa.me/919004963174">+91 9004963174</a></td></tr>
  	      <tr><td>Pritam Bhalerao</td><td>{{d.pritam}}</td><td><a href="https://wa.me/919594133129">+91 9594133129</a></td></tr>
        </table>
      </div>


      {% endfor %}

    {% else %}
    <p>No Record Found</p>
    {% endif %}
    </div>
  {% endblock %}